name: Update Dalamud Plugins

on:
  push:
    branches: [ main, master ]  # 主分支提交时触发
    paths-ignore:
      - 'myrepo.json'  # 忽略插件数据文件的更改，避免无限循环
      - 'plugins/**'   # 忽略插件目录的更改
      - '*.md'         # 忽略文档文件的更改
  pull_request:
    branches: [ main, master ]  # PR时也触发
  schedule:
    - cron: '0 */8 * * *'  # 保留定时运行作为备份（每8小时）
  workflow_dispatch:  # 允许手动触发

jobs:
  update-plugins:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    env:
      TZ: 'Asia/Shanghai'  # 设置时区为东八区
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set timezone
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        echo "当前时间: $(date +'%Y-%m-%d %H:%M:%S %Z')"
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run plugin updater
      run: |
        python plugin_updater.py
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-update plugins $(date +'%Y-%m-%d %H:%M:%S %Z')"
        git push
